AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys the lambda function for ec2manger and the API Gateway integration that calls it

Parameters:
  Environment:
    Description: Environment of the stack being deployed
    Type: String
    Default: prod
  CognitoUserPool:
    Description: The userpool ARN to use for API Gateway
    Type: String
    Default: "arn:aws:cognito-idp:us-west-2:606263411016:userpool/us-west-2_Am7HV1JyI"

Resources:
  ec2ManagerStopStartIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Statement:
          -
            Sid: "AllowLambdaToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        -
          PolicyName: "ec2ManagerStopStart"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Sid: "AllowLambdaToStartStopEC2"
                Effect: "Allow"
                Action:
                  - "ec2:Start*"
                  - "ec2:Stop*"
                  - "ec2:Describe*"
                  - "ec2:RunInstances"
                  - "ec2:TerminateInstances"
                Resource: "*"
  

      #aws cloudformation update-stack --stack-name ec2manager --template-body file://ec2manager.yml --profile cpe453 --capabilities CAPABILITY_IAM
  